CREATE TABLE users (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     email VARCHAR(255) NOT NULL,
                     password_hash VARCHAR(255) NOT NULL,
                     full_name VARCHAR(150) NOT NULL,
                     phone VARCHAR(30),
                     status VARCHAR(20) NOT NULL,
                     created_at TIMESTAMPTZ NOT NULL,
                     updated_at TIMESTAMPTZ NOT NULL,
                     CONSTRAINT uk_users_email UNIQUE (email),
                     CONSTRAINT ck_users_email_not_blank CHECK (btrim(email) <> ''),
                     CONSTRAINT ck_users_full_name_not_blank CHECK (btrim(full_name) <> ''),
                     CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'LOCKED', 'PENDING'))
);
