CREATE TABLE stores (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      owner_user_id BIGINT NOT NULL,
                      name VARCHAR(150) NOT NULL,
                      phone VARCHAR(30),
                      address_line VARCHAR(255) NOT NULL,
                      auto_accept_default BOOLEAN NOT NULL DEFAULT FALSE,
                      status VARCHAR(20) NOT NULL,
                      created_at TIMESTAMPTZ NOT NULL,
                      updated_at TIMESTAMPTZ NOT NULL,
                      CONSTRAINT uk_stores_owner_user_id UNIQUE (owner_user_id),
                      CONSTRAINT ck_stores_name_not_blank CHECK (btrim(name) <> ''),
                      CONSTRAINT ck_stores_address_not_blank CHECK (btrim(address_line) <> ''),
                      CONSTRAINT ck_stores_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
                      CONSTRAINT fk_stores_owner_user
                        FOREIGN KEY (owner_user_id) REFERENCES users (id)
);
