CREATE TABLE categories (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          description VARCHAR(255),
                          is_active BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at TIMESTAMPTZ NOT NULL,
                          updated_at TIMESTAMPTZ NOT NULL,
                          CONSTRAINT uk_categories_name UNIQUE (name),
                          CONSTRAINT ck_categories_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE store_categories (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                store_id BIGINT NOT NULL,
                                category_id BIGINT NOT NULL,
                                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                display_order INTEGER NOT NULL DEFAULT 0,
                                created_at TIMESTAMPTZ NOT NULL,
                                updated_at TIMESTAMPTZ NOT NULL,
                                CONSTRAINT uk_store_categories_store_category UNIQUE (store_id, category_id),
                                CONSTRAINT ck_store_categories_display_order CHECK (display_order >= 0),
                                CONSTRAINT fk_store_categories_store
                                  FOREIGN KEY (store_id) REFERENCES stores (id),
                                CONSTRAINT fk_store_categories_category
                                  FOREIGN KEY (category_id) REFERENCES categories (id)
);
