CREATE TABLE products (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        store_id BIGINT NOT NULL,
                        store_category_id BIGINT NOT NULL,
                        name VARCHAR(150) NOT NULL,
                        description TEXT,
                        image_url VARCHAR(500),
                        is_active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMPTZ NOT NULL,
                        updated_at TIMESTAMPTZ NOT NULL,
                        CONSTRAINT uk_products_store_name UNIQUE (store_id, name),
                        CONSTRAINT ck_products_name_not_blank CHECK (btrim(name) <> ''),
                        CONSTRAINT fk_products_store
                          FOREIGN KEY (store_id) REFERENCES stores (id),
                        CONSTRAINT fk_products_store_category
                          FOREIGN KEY (store_category_id) REFERENCES store_categories (id)
);

CREATE TABLE product_variants (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                product_id BIGINT NOT NULL,
                                name VARCHAR(80) NOT NULL,
                                size VARCHAR(30),
                                price NUMERIC(12, 2) NOT NULL,
                                inventory_mode VARCHAR(30) NOT NULL,
                                auto_accept_override BOOLEAN,
                                max_quantity_per_order INTEGER,
                                is_available BOOLEAN NOT NULL DEFAULT TRUE,
                                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                created_at TIMESTAMPTZ NOT NULL,
                                updated_at TIMESTAMPTZ NOT NULL,
                                CONSTRAINT uk_product_variants_product_name UNIQUE (product_id, name),
                                CONSTRAINT ck_product_variants_name_not_blank CHECK (btrim(name) <> ''),
                                CONSTRAINT ck_product_variants_price_non_negative CHECK (price >= 0),
                                CONSTRAINT ck_product_variants_inventory_mode
                                  CHECK (inventory_mode IN ('MADE_TO_ORDER', 'LIMITED_STOCK')),
                                CONSTRAINT ck_product_variants_max_quantity_positive
                                  CHECK (max_quantity_per_order IS NULL OR max_quantity_per_order > 0),
                                CONSTRAINT fk_product_variants_product
                                  FOREIGN KEY (product_id) REFERENCES products (id)
);
