-- FF-02-01-1 / FreshFlow database foundation
-- Database-first schema for all 23 tables in the approved FreshFlow ERD.
-- Tables are created in dependency order. No JPA entity is generated by this file.
-- ProductVariant has no code column: name identifies a variant within its Product.

-- 1. Identity foundation
CREATE TABLE users (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     email VARCHAR(255) NOT NULL,
                     password_hash VARCHAR(255) NOT NULL,
                     full_name VARCHAR(150) NOT NULL,
                     phone VARCHAR(30),
                     status VARCHAR(20) NOT NULL,
                     created_at TIMESTAMPTZ NOT NULL,
                     updated_at TIMESTAMPTZ NOT NULL,
                     CONSTRAINT uk_users_email UNIQUE (email),
                     CONSTRAINT ck_users_email_not_blank CHECK (btrim(email) <> ''),
                     CONSTRAINT ck_users_full_name_not_blank CHECK (btrim(full_name) <> ''),
                     CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'LOCKED', 'PENDING'))
);

CREATE TABLE roles (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     code VARCHAR(30) NOT NULL,
                     name VARCHAR(80) NOT NULL,
                     created_at TIMESTAMPTZ NOT NULL,
                     CONSTRAINT uk_roles_code UNIQUE (code),
                     CONSTRAINT ck_roles_code_not_blank CHECK (btrim(code) <> ''),
                     CONSTRAINT ck_roles_code_uppercase CHECK (code = upper(code)),
                     CONSTRAINT ck_roles_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE stores (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      owner_user_id BIGINT NOT NULL,
                      name VARCHAR(150) NOT NULL,
                      phone VARCHAR(30),
                      address_line VARCHAR(255) NOT NULL,
                      auto_accept_default BOOLEAN NOT NULL DEFAULT FALSE,
                      status VARCHAR(20) NOT NULL,
                      created_at TIMESTAMPTZ NOT NULL,
                      updated_at TIMESTAMPTZ NOT NULL,
                      CONSTRAINT uk_stores_owner_user_id UNIQUE (owner_user_id),
                      CONSTRAINT ck_stores_name_not_blank CHECK (btrim(name) <> ''),
                      CONSTRAINT ck_stores_address_not_blank CHECK (btrim(address_line) <> ''),
                      CONSTRAINT ck_stores_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
                      CONSTRAINT fk_stores_owner_user
                        FOREIGN KEY (owner_user_id) REFERENCES users (id)
);

CREATE TABLE user_store_roles (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id BIGINT NOT NULL,
                                store_id BIGINT NOT NULL,
                                role_id BIGINT NOT NULL,
                                status VARCHAR(20) NOT NULL,
                                created_at TIMESTAMPTZ NOT NULL,
                                updated_at TIMESTAMPTZ NOT NULL,
                                CONSTRAINT uk_user_store_roles_assignment UNIQUE (user_id, store_id, role_id),
                                CONSTRAINT ck_user_store_roles_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
                                CONSTRAINT fk_user_store_roles_user
                                  FOREIGN KEY (user_id) REFERENCES users (id),
                                CONSTRAINT fk_user_store_roles_store
                                  FOREIGN KEY (store_id) REFERENCES stores (id),
                                CONSTRAINT fk_user_store_roles_role
                                  FOREIGN KEY (role_id) REFERENCES roles (id)
);

-- 2. Driver foundation
CREATE TABLE driver_profiles (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               store_id BIGINT NOT NULL,
                               is_available BOOLEAN NOT NULL DEFAULT FALSE,
                               vehicle_type VARCHAR(30),
                               status VARCHAR(20) NOT NULL,
                               created_at TIMESTAMPTZ NOT NULL,
                               updated_at TIMESTAMPTZ NOT NULL,
                               CONSTRAINT uk_driver_profiles_user UNIQUE (user_id),
                               CONSTRAINT ck_driver_profiles_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'INACTIVE')),
                               CONSTRAINT fk_driver_profiles_user
                                 FOREIGN KEY (user_id) REFERENCES users (id),
                               CONSTRAINT fk_driver_profiles_store
                                 FOREIGN KEY (store_id) REFERENCES stores (id)
);

-- Canonical ERD name: driver_availability_history.
CREATE TABLE driver_availability_history (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           driver_profile_id BIGINT NOT NULL,
                                           is_available BOOLEAN NOT NULL,
                                           changed_by_user_id BIGINT NOT NULL,
                                           changed_at TIMESTAMPTZ NOT NULL,
                                           reason VARCHAR(255),
                                           CONSTRAINT fk_driver_availability_history_driver
                                             FOREIGN KEY (driver_profile_id) REFERENCES driver_profiles (id),
                                           CONSTRAINT fk_driver_availability_history_actor
                                             FOREIGN KEY (changed_by_user_id) REFERENCES users (id)
);

-- 3. Catalog
CREATE TABLE categories (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          description VARCHAR(255),
                          is_active BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at TIMESTAMPTZ NOT NULL,
                          updated_at TIMESTAMPTZ NOT NULL,
                          CONSTRAINT uk_categories_name UNIQUE (name),
                          CONSTRAINT ck_categories_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE store_categories (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                store_id BIGINT NOT NULL,
                                category_id BIGINT NOT NULL,
                                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                display_order INTEGER NOT NULL DEFAULT 0,
                                created_at TIMESTAMPTZ NOT NULL,
                                updated_at TIMESTAMPTZ NOT NULL,
                                CONSTRAINT uk_store_categories_store_category UNIQUE (store_id, category_id),
                                CONSTRAINT uk_store_categories_store_id_id UNIQUE (store_id, id),
                                CONSTRAINT ck_store_categories_display_order CHECK (display_order >= 0),
                                CONSTRAINT fk_store_categories_store
                                  FOREIGN KEY (store_id) REFERENCES stores (id),
                                CONSTRAINT fk_store_categories_category
                                  FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE products (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        store_id BIGINT NOT NULL,
                        store_category_id BIGINT NOT NULL,
                        name VARCHAR(150) NOT NULL,
                        description TEXT,
                        image_url VARCHAR(500),
                        is_active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMPTZ NOT NULL,
                        updated_at TIMESTAMPTZ NOT NULL,
                        CONSTRAINT uk_products_store_name UNIQUE (store_id, name),
                        CONSTRAINT ck_products_name_not_blank CHECK (btrim(name) <> ''),
                        CONSTRAINT fk_products_store
                          FOREIGN KEY (store_id) REFERENCES stores (id),
                        CONSTRAINT fk_products_store_category
                          FOREIGN KEY (store_id, store_category_id)
                            REFERENCES store_categories (store_id, id)
);

CREATE TABLE product_variants (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                product_id BIGINT NOT NULL,
                                name VARCHAR(80) NOT NULL,
                                size VARCHAR(30),
                                price NUMERIC(12, 2) NOT NULL,
                                inventory_mode VARCHAR(30) NOT NULL,
                                auto_accept_override BOOLEAN,
                                max_quantity_per_order INTEGER,
                                is_available BOOLEAN NOT NULL DEFAULT TRUE,
                                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                created_at TIMESTAMPTZ NOT NULL,
                                updated_at TIMESTAMPTZ NOT NULL,
                                CONSTRAINT uk_product_variants_product_name UNIQUE (product_id, name),
                                CONSTRAINT ck_product_variants_name_not_blank CHECK (btrim(name) <> ''),
                                CONSTRAINT ck_product_variants_price_non_negative CHECK (price >= 0),
                                CONSTRAINT ck_product_variants_inventory_mode
                                  CHECK (inventory_mode IN ('MADE_TO_ORDER', 'LIMITED_STOCK')),
                                CONSTRAINT ck_product_variants_max_quantity_positive
                                  CHECK (max_quantity_per_order IS NULL OR max_quantity_per_order > 0),
                                CONSTRAINT fk_product_variants_product
                                  FOREIGN KEY (product_id) REFERENCES products (id)
);

-- 4. Inventory and capacity
CREATE TABLE inventory_locations (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   store_id BIGINT NOT NULL,
                                   name VARCHAR(100) NOT NULL,
                                   type VARCHAR(30) NOT NULL,
                                   is_default BOOLEAN NOT NULL DEFAULT FALSE,
                                   is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                   created_at TIMESTAMPTZ NOT NULL,
                                   updated_at TIMESTAMPTZ NOT NULL,
                                   CONSTRAINT uk_inventory_locations_store_name UNIQUE (store_id, name),
                                   CONSTRAINT ck_inventory_locations_name_not_blank CHECK (btrim(name) <> ''),
                                   CONSTRAINT ck_inventory_locations_type CHECK (type IN ('MAIN_KITCHEN', 'WAREHOUSE')),
                                   CONSTRAINT fk_inventory_locations_store
                                     FOREIGN KEY (store_id) REFERENCES stores (id)
);

CREATE TABLE inventory_stock_records (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       variant_id BIGINT NOT NULL,
                                       location_id BIGINT NOT NULL,
                                       stock_quantity INTEGER NOT NULL,
                                       reserved_quantity INTEGER NOT NULL DEFAULT 0,
                                       version BIGINT NOT NULL DEFAULT 0,
                                       updated_at TIMESTAMPTZ NOT NULL,
                                       CONSTRAINT uk_inventory_stock_variant_location UNIQUE (variant_id, location_id),
                                       CONSTRAINT ck_inventory_stock_quantity_non_negative CHECK (stock_quantity >= 0),
                                       CONSTRAINT ck_inventory_stock_reserved_non_negative CHECK (reserved_quantity >= 0),
                                       CONSTRAINT ck_inventory_stock_reserved_within_stock CHECK (reserved_quantity <= stock_quantity),
                                       CONSTRAINT ck_inventory_stock_version_non_negative CHECK (version >= 0),
                                       CONSTRAINT fk_inventory_stock_variant
                                         FOREIGN KEY (variant_id) REFERENCES product_variants (id),
                                       CONSTRAINT fk_inventory_stock_location
                                         FOREIGN KEY (location_id) REFERENCES inventory_locations (id)
);

CREATE TABLE inventory_capacity_records (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          variant_id BIGINT NOT NULL,
                                          location_id BIGINT NOT NULL,
                                          capacity_date DATE NOT NULL,
                                          capacity_limit INTEGER NOT NULL,
                                          reserved_quantity INTEGER NOT NULL DEFAULT 0,
                                          version BIGINT NOT NULL DEFAULT 0,
                                          created_at TIMESTAMPTZ NOT NULL,
                                          updated_at TIMESTAMPTZ NOT NULL,
                                          CONSTRAINT uk_inventory_capacity_variant_location_date
                                            UNIQUE (variant_id, location_id, capacity_date),
                                          CONSTRAINT ck_inventory_capacity_limit_non_negative CHECK (capacity_limit >= 0),
                                          CONSTRAINT ck_inventory_capacity_reserved_non_negative CHECK (reserved_quantity >= 0),
                                          CONSTRAINT ck_inventory_capacity_reserved_within_limit
                                            CHECK (reserved_quantity <= capacity_limit),
                                          CONSTRAINT ck_inventory_capacity_version_non_negative CHECK (version >= 0),
                                          CONSTRAINT fk_inventory_capacity_variant
                                            FOREIGN KEY (variant_id) REFERENCES product_variants (id),
                                          CONSTRAINT fk_inventory_capacity_location
                                            FOREIGN KEY (location_id) REFERENCES inventory_locations (id)
);

-- 5. Cart and order
CREATE TABLE carts (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     customer_user_id BIGINT NOT NULL,
                     store_id BIGINT NOT NULL,
                     status VARCHAR(20) NOT NULL,
                     created_at TIMESTAMPTZ NOT NULL,
                     updated_at TIMESTAMPTZ NOT NULL,
                     CONSTRAINT ck_carts_status CHECK (status IN ('ACTIVE', 'CHECKED_OUT', 'ABANDONED')),
                     CONSTRAINT fk_carts_customer
                       FOREIGN KEY (customer_user_id) REFERENCES users (id),
                     CONSTRAINT fk_carts_store
                       FOREIGN KEY (store_id) REFERENCES stores (id)
);

CREATE TABLE cart_items (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          cart_id BIGINT NOT NULL,
                          variant_id BIGINT NOT NULL,
                          quantity INTEGER NOT NULL,
                          created_at TIMESTAMPTZ NOT NULL,
                          updated_at TIMESTAMPTZ NOT NULL,
                          CONSTRAINT uk_cart_items_cart_variant UNIQUE (cart_id, variant_id),
                          CONSTRAINT ck_cart_items_quantity_positive CHECK (quantity > 0),
                          CONSTRAINT fk_cart_items_cart
                            FOREIGN KEY (cart_id) REFERENCES carts (id),
                          CONSTRAINT fk_cart_items_variant
                            FOREIGN KEY (variant_id) REFERENCES product_variants (id)
);

CREATE TABLE orders (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      order_number VARCHAR(30) NOT NULL,
                      customer_user_id BIGINT NOT NULL,
                      store_id BIGINT NOT NULL,
                      current_driver_id BIGINT,
                      status VARCHAR(40) NOT NULL,
                      payment_method VARCHAR(40) NOT NULL,
                      merchant_acceptance_status VARCHAR(20) NOT NULL,
                      subtotal NUMERIC(12, 2) NOT NULL,
                      delivery_fee NUMERIC(12, 2) NOT NULL DEFAULT 0,
                      discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
                      total_amount NUMERIC(12, 2) NOT NULL,
                      cancel_reason VARCHAR(80),
                      created_at TIMESTAMPTZ NOT NULL,
                      accepted_at TIMESTAMPTZ,
                      processing_at TIMESTAMPTZ,
                      completed_at TIMESTAMPTZ,
                      cancelled_at TIMESTAMPTZ,
                      updated_at TIMESTAMPTZ NOT NULL,
                      CONSTRAINT uk_orders_order_number UNIQUE (order_number),
                      CONSTRAINT ck_orders_order_number_not_blank CHECK (btrim(order_number) <> ''),
                      CONSTRAINT ck_orders_status CHECK (
                        status IN (
                                   'AWAITING_MERCHANT_CONFIRMATION',
                                   'AWAITING_PAYMENT',
                                   'PENDING',
                                   'PROCESSING',
                                   'SHIPPING',
                                   'DELIVERY_FAILED',
                                   'DISPUTED',
                                   'COMPLETED',
                                   'CANCELLED'
                          )
                        ),
                      CONSTRAINT ck_orders_payment_method CHECK (
                        payment_method IN (
                                           'ONLINE_MOCK',
                                           'CASH_ON_DELIVERY',
                                           'BANK_TRANSFER_ON_DELIVERY'
                          )
                        ),
                      CONSTRAINT ck_orders_acceptance_status CHECK (
                        merchant_acceptance_status IN ('PENDING', 'ACCEPTED', 'REJECTED')
                        ),
                      CONSTRAINT ck_orders_subtotal_non_negative CHECK (subtotal >= 0),
                      CONSTRAINT ck_orders_delivery_fee_non_negative CHECK (delivery_fee >= 0),
                      CONSTRAINT ck_orders_discount_non_negative CHECK (discount_amount >= 0),
                      CONSTRAINT ck_orders_total_non_negative CHECK (total_amount >= 0),
                      CONSTRAINT fk_orders_customer
                        FOREIGN KEY (customer_user_id) REFERENCES users (id),
                      CONSTRAINT fk_orders_store
                        FOREIGN KEY (store_id) REFERENCES stores (id),
                      CONSTRAINT fk_orders_current_driver
                        FOREIGN KEY (current_driver_id) REFERENCES driver_profiles (id)
);

CREATE TABLE order_items (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           order_id BIGINT NOT NULL,
                           product_id BIGINT,
                           product_variant_id BIGINT NOT NULL,
                           product_name_snapshot VARCHAR(150) NOT NULL,
                           variant_name_snapshot VARCHAR(80) NOT NULL,
                           unit_price_snapshot NUMERIC(12, 2) NOT NULL,
                           quantity INTEGER NOT NULL,
                           line_total NUMERIC(12, 2) NOT NULL,
                           CONSTRAINT ck_order_items_product_name_not_blank CHECK (btrim(product_name_snapshot) <> ''),
                           CONSTRAINT ck_order_items_variant_name_not_blank CHECK (btrim(variant_name_snapshot) <> ''),
                           CONSTRAINT ck_order_items_unit_price_non_negative CHECK (unit_price_snapshot >= 0),
                           CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0),
                           CONSTRAINT ck_order_items_line_total_non_negative CHECK (line_total >= 0),
                           CONSTRAINT fk_order_items_order
                             FOREIGN KEY (order_id) REFERENCES orders (id),
                           CONSTRAINT fk_order_items_product
                             FOREIGN KEY (product_id) REFERENCES products (id),
                           CONSTRAINT fk_order_items_product_variant
                             FOREIGN KEY (product_variant_id) REFERENCES product_variants (id)
);

-- 6. Payment and idempotency
CREATE TABLE payments (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id BIGINT NOT NULL,
                        attempt_number INTEGER NOT NULL,
                        method VARCHAR(40) NOT NULL,
                        status VARCHAR(30) NOT NULL,
                        amount NUMERIC(12, 2) NOT NULL,
                        provider_reference VARCHAR(120),
                        failure_reason VARCHAR(255),
                        paid_at TIMESTAMPTZ,
                        refunded_at TIMESTAMPTZ,
                        created_at TIMESTAMPTZ NOT NULL,
                        updated_at TIMESTAMPTZ NOT NULL,
                        CONSTRAINT uk_payments_order_attempt UNIQUE (order_id, attempt_number),
                        CONSTRAINT ck_payments_attempt_positive CHECK (attempt_number >= 1),
                        CONSTRAINT ck_payments_method CHECK (
                          method IN ('ONLINE_MOCK', 'CASH_ON_DELIVERY', 'BANK_TRANSFER_ON_DELIVERY')
                          ),
                        CONSTRAINT ck_payments_status CHECK (
                          status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED',
                                     'CASH_COLLECTED', 'TRANSFER_CONFIRMED', 'EXPIRED')
                          ),
                        CONSTRAINT ck_payments_amount_non_negative CHECK (amount >= 0),
                        CONSTRAINT fk_payments_order
                          FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE TABLE idempotency_records (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   user_id BIGINT NOT NULL,
                                   idempotency_key VARCHAR(120) NOT NULL,
                                   request_hash VARCHAR(128) NOT NULL,
                                   order_id BIGINT,
                                   response_status INTEGER,
                                   response_body JSONB,
                                   expires_at TIMESTAMPTZ NOT NULL,
                                   created_at TIMESTAMPTZ NOT NULL,
                                   CONSTRAINT uk_idempotency_user_key UNIQUE (user_id, idempotency_key),
                                   CONSTRAINT ck_idempotency_key_not_blank CHECK (btrim(idempotency_key) <> ''),
                                   CONSTRAINT ck_idempotency_request_hash_not_blank CHECK (btrim(request_hash) <> ''),
                                   CONSTRAINT ck_idempotency_response_status_valid
                                     CHECK (response_status IS NULL OR response_status BETWEEN 100 AND 599),
                                   CONSTRAINT fk_idempotency_user
                                     FOREIGN KEY (user_id) REFERENCES users (id),
                                   CONSTRAINT fk_idempotency_order
                                     FOREIGN KEY (order_id) REFERENCES orders (id)
);

-- 7. Delivery and credentials
CREATE TABLE delivery_assignments (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    order_id BIGINT NOT NULL,
                                    driver_profile_id BIGINT NOT NULL,
                                    status VARCHAR(30) NOT NULL,
                                    attempt_number INTEGER NOT NULL,
                                    assigned_at TIMESTAMPTZ NOT NULL,
                                    dispatched_at TIMESTAMPTZ,
                                    delivered_at TIMESTAMPTZ,
                                    ended_at TIMESTAMPTZ,
                                    failure_reason VARCHAR(255),
                                    created_at TIMESTAMPTZ NOT NULL,
                                    updated_at TIMESTAMPTZ NOT NULL,
                                    CONSTRAINT uk_delivery_assignments_order_attempt UNIQUE (order_id, attempt_number),
                                    CONSTRAINT ck_delivery_assignments_status CHECK (
                                      status IN ('ASSIGNED', 'DISPATCHED', 'DELIVERING', 'DELIVERED', 'FAILED', 'ENDED')
                                      ),
                                    CONSTRAINT ck_delivery_assignments_attempt_positive CHECK (attempt_number >= 1),
                                    CONSTRAINT fk_delivery_assignments_order
                                      FOREIGN KEY (order_id) REFERENCES orders (id),
                                    CONSTRAINT fk_delivery_assignments_driver
                                      FOREIGN KEY (driver_profile_id) REFERENCES driver_profiles (id)
);

CREATE TABLE delivery_credentials (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    delivery_assignment_id BIGINT NOT NULL,
                                    otp_hash VARCHAR(255) NOT NULL,
                                    expires_at TIMESTAMPTZ NOT NULL,
                                    used_at TIMESTAMPTZ,
                                    attempt_count INTEGER NOT NULL DEFAULT 0,
                                    max_attempts INTEGER NOT NULL,
                                    created_at TIMESTAMPTZ NOT NULL,
                                    CONSTRAINT ck_delivery_credentials_otp_hash_not_blank CHECK (btrim(otp_hash) <> ''),
                                    CONSTRAINT ck_delivery_credentials_attempt_count_non_negative CHECK (attempt_count >= 0),
                                    CONSTRAINT ck_delivery_credentials_max_attempts_positive CHECK (max_attempts > 0),
                                    CONSTRAINT ck_delivery_credentials_attempts_within_limit
                                      CHECK (attempt_count <= max_attempts),
                                    CONSTRAINT fk_delivery_credentials_assignment
                                      FOREIGN KEY (delivery_assignment_id) REFERENCES delivery_assignments (id)
);

-- 8. Dispute and audit
CREATE TABLE disputes (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id BIGINT NOT NULL,
                        customer_user_id BIGINT NOT NULL,
                        reason VARCHAR(60) NOT NULL,
                        customer_message TEXT NOT NULL,
                        status VARCHAR(30) NOT NULL,
                        merchant_resolution TEXT,
                        resolved_by_user_id BIGINT,
                        resolved_at TIMESTAMPTZ,
                        created_at TIMESTAMPTZ NOT NULL,
                        updated_at TIMESTAMPTZ NOT NULL,
                        CONSTRAINT ck_disputes_reason_not_blank CHECK (btrim(reason) <> ''),
                        CONSTRAINT ck_disputes_customer_message_not_blank CHECK (btrim(customer_message) <> ''),
                        CONSTRAINT ck_disputes_status CHECK (
                          status IN ('OPEN', 'RESOLVED_DELIVERED', 'RESOLVED_CANCELLED')
                          ),
                        CONSTRAINT fk_disputes_order
                          FOREIGN KEY (order_id) REFERENCES orders (id),
                        CONSTRAINT fk_disputes_customer
                          FOREIGN KEY (customer_user_id) REFERENCES users (id),
                        CONSTRAINT fk_disputes_resolver
                          FOREIGN KEY (resolved_by_user_id) REFERENCES users (id)
);

CREATE TABLE order_audits (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            order_id BIGINT NOT NULL,
                            actor_user_id BIGINT,
                            actor_role VARCHAR(30),
                            event_type VARCHAR(50) NOT NULL,
                            from_status VARCHAR(40),
                            to_status VARCHAR(40),
                            reason VARCHAR(255),
                            metadata JSONB,
                            created_at TIMESTAMPTZ NOT NULL,
                            CONSTRAINT ck_order_audits_event_type_not_blank CHECK (btrim(event_type) <> ''),
                            CONSTRAINT fk_order_audits_order
                              FOREIGN KEY (order_id) REFERENCES orders (id),
                            CONSTRAINT fk_order_audits_actor
                              FOREIGN KEY (actor_user_id) REFERENCES users (id)
);

-- 9. Policy-specific indexes
CREATE UNIQUE INDEX uk_carts_active_customer_store
  ON carts (customer_user_id, store_id)
  WHERE status = 'ACTIVE';

CREATE UNIQUE INDEX uk_inventory_locations_default_store
  ON inventory_locations (store_id)
  WHERE is_default = TRUE;

CREATE UNIQUE INDEX uk_payments_provider_reference
  ON payments (provider_reference)
  WHERE provider_reference IS NOT NULL;

CREATE UNIQUE INDEX uk_payments_online_success_order
  ON payments (order_id)
  WHERE method = 'ONLINE_MOCK' AND status = 'SUCCEEDED';

CREATE UNIQUE INDEX uk_delivery_assignments_active_order
  ON delivery_assignments (order_id)
  WHERE status IN ('ASSIGNED', 'DISPATCHED', 'DELIVERING');

CREATE INDEX idx_products_store_category
  ON products (store_id, store_category_id);

CREATE INDEX idx_product_variants_product_active
  ON product_variants (product_id, is_active, is_available);

CREATE INDEX idx_inventory_capacity_variant_date
  ON inventory_capacity_records (variant_id, capacity_date);

CREATE INDEX idx_orders_customer_created_at
  ON orders (customer_user_id, created_at DESC);

CREATE INDEX idx_orders_store_status_created_at
  ON orders (store_id, status, created_at DESC);

CREATE INDEX idx_delivery_assignments_driver_status
  ON delivery_assignments (driver_profile_id, status);

CREATE INDEX idx_order_audits_order_created_at
  ON order_audits (order_id, created_at DESC);
