package com.freshflow.api.catalog.application.exception;

public enum CatalogErrorCode {
  USER_NOT_FOUND("CATALOG_USER_NOT_FOUND"),
  STORE_NOT_FOUND("CATALOG_STORE_NOT_FOUND"),
  STORE_ACCESS_DENIED("CATALOG_STORE_ACCESS_DENIED"),
  ACTOR_REQUIRED("CATALOG_ACTOR_REQUIRED"),
  CATEGORY_NOT_FOUND("CATALOG_CATEGORY_NOT_FOUND"),
  STORE_CATEGORY_NOT_FOUND("CATALOG_STORE_CATEGORY_NOT_FOUND"),
  STORE_CATEGORY_OWNERSHIP_MISMATCH("CATALOG_STORE_CATEGORY_OWNERSHIP_MISMATCH"),
  PRODUCT_NOT_FOUND("CATALOG_PRODUCT_NOT_FOUND"),
  VARIANT_NOT_FOUND("CATALOG_VARIANT_NOT_FOUND"),
  VARIANT_DUPLICATE("CATALOG_VARIANT_DUPLICATE"),
  STANDARD_SIZE_INVALID("CATALOG_STANDARD_SIZE_INVALID"),
  VALIDATION_ERROR("VALIDATION_ERROR"),
  CONFLICT("CATALOG_CONFLICT");

  private final String code;

  CatalogErrorCode(String code) {
    this.code = code;
  }

  public String code() {
    return code;
  }
}
